services:
  main:
    build: ./main
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - python-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/server_database
    env_file:
      - ./main/.env

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  python-service:
    build: ./python_service

volumes:
  mongodb_data:
